version: '3'

services:
  base-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: base-api
    restart: unless-stopped
    tty: true
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - '1337:1337'
    command: yarn develop
